#!/bin/bash

xgettext --language=Python --keyword=_ --output=folder-color-switcher.pot \
  usr/share/nemo-python/extensions/nemo-folder-color-switcher.py \
  usr/share/caja-python/extensions/caja-folder-color-switcher.py
